import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { type AppType } from "next/app";
import { api } from "@/utils/api";
import "@/styles/globals.css";
import Head from "next/head";
import { cn } from "@/utils/helpers";
import { Jost } from "next/font/google";
import { SkeletonTheme } from "react-loading-skeleton";

const jost = Jost({ subsets: ["latin"] });
const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
      <SkeletonTheme baseColor="#FFFFFF" highlightColor="#e6e8ec">
        <Head>
          <title>Movie Takes!</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={cn("min-h-screen bg-white-200 ", jost.className)}>
          <Component {...pageProps} />
        </main>
      </SkeletonTheme>
    </SessionProvider>
  );
};

export default api.withTRPC(MyApp);
